frame_id: map
initial_pose:
  x: 0.454
  y: -2.226
  yaw: 1.541
waypoints:
- name: wp1
  x: -0.074
  y: -3.96
  yaw: 1.626
- name: wp2
  x: 0.454
  y: -2.226
  yaw: 1.541
- name: wp3
  x: 0.446
  y: 0.587
  yaw: 1.37
